name: CI
on: [push]
jobs:
  container:
    runs-on: ubuntu-latest
    container: dohubin/synologywireguardbuilderdocker:latest
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
        name: Run in container
    
