name: CI
on: [push]
jobs:
  myjob:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    # Those steps are executed directly on the VM
    - run: ls /
    - run: echo $HOME
    - name: Add a file
      run: touch $HOME/stuff.txt
    # Those steps are actions, which may run inside a container
    - run:  |
          IS_IN_CONTAINER=1
          PACKAGE_ARCH=apollolake
          DSM_VER=6.2
          bash build.sh
    - uses: actions/checkout@v1
    
    - uses: docker://dohubin/synologywireguardbuilderdocker:latest
