name: MultiBuild
'on':
  - push
jobs:
  build_1_apollolake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SPK Generation
        run: sudo bash multi_build.sh apollolake
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: apollolake
          path: target
  build_2_armada38x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SPK Generation
        run: sudo bash multi_build.sh armada38x
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}
          path: target
  build_3_avoton:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SPK Generation
        run: sudo bash multi_build.sh avoton
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job.name }}
          path: target
