name: Docker Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: LS
      run: ls -lah && ls -lah /
    - name: Build
      run: bash release.sh
