name: Docker Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: LS
      run: ls -lah && ls -lah /
    - name: Build
      run: sudo bash release.sh
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts 
