name: Docker Run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: LS
      run: ls -lah && ls -lah /
    - name: Cache Tarballs
      uses: actions/cache@v2
      env:
        cache-name: cache-tarballs
      with:
        path: /toolkit_tarnballs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/base_env-6.2.txz') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
 
    - name: Build the Docker image
      run: docker build -t synobuild . --file Dockerfile
    - name: LS
      run: ls -lah && ls -lah /
    - name: Run
      run: sudo docker run --rm --privileged --env PACKAGE_ARCH=armada38x --env DSM_VER=6.2 -v $(pwd)/artifacts:/result_spk synobuild
    - name: LS A
      run: ls -lah artifacts
    - name: LS tarballs
      run: ls -lahR artifacts
    - name: pwd
      run: pwd
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: artifacts # or path/to/artifact
