name: WORKFLOW_BUILD
on: [push]
jobs:
  build:
    runs-on: dohubin/synologywireguardbuilderdocker:latest
    env:
        IS_IN_CONTAINER: 1
        PACKAGE_ARCH: x64
        DSM_VER: 6.2
    steps:
    # Those steps are executed directly on the VM
    - run: echo $HOME
    - uses: actions/checkout@v1
    - run: ls -lah
    - run: bash build.sh
