name: WORKFLOW_BUILD
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
    - uses: actions/checkout@v1      
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        MY_ENV_VAR: 'my value'

    - name: Printenv
      run: |
        echo "MY_ENV_VAR=${MY_ENV_VAR}"
        printenv
