name: WORKFLOW_BUILD
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
        IS_IN_CONTAINER: 1
        PACKAGE_ARCH: x64
        DSM_VER: 6.2
    steps:
    # Those steps are executed directly on the VM
    - run: sudo apt-get update && sudo apt-get -qy install git python3 wget ca-certificates xz-utils
    - run: echo $HOME
    - uses: actions/checkout@v1
    - run: sudo ls -lah
    - run: sudo bash build.sh
